from hfsm import State, Event, StateMachine

peur = State("peur")
faim = State("faim")
bien = State("bien")
recevoir_nourriture = Event("recevoir_nourriture")
ennemi_arrive = Event("ennemei_arrive")
ami_arrive = Event("ami_arrive")
ennemi_quitte = Event("ennemi_quitte")
recevoir_nourriture = Event("recevoir_nourriture")
fsm = StateMachine("fsm")

fsm.add_state(bien, initial_state=True)
fsm.add_state(faim)
fsm.add_state(peur)
fsm.add_event(recevoir_nourriture)
fsm.add_event(ennemi_arrive)
fsm.add_event(ennemi_quitte)
fsm.add_event(ami_arrive)
fsm.add_transition(faim, bien, recevoir_nourriture)
fsm.add_transition(faim, peur, ennemi_arrive)
fsm.add_transition(faim, faim, ami_arrive)
fsm.add_transition(faim, peur, ennemi_quitte)
fsm.add_transition(bien, bien, recevoir_nourriture)
fsm.add_transition(bien, peur, ennemi_arrive)
fsm.add_transition(bien, bien, ami_arrive)
fsm.add_transition(bien, bien, ennemi_quitte)
fsm.add_transition(peur, peur, recevoir_nourriture)
fsm.add_transition(peur, peur, ennemi_arrive)
fsm.add_transition(peur, bien, ami_arrive)
fsm.add_transition(peur, bien, ennemi_quitte)
fsm.start("data")
fsm.trigger_event(ami_arrive)
print(fsm._current_state)